name: Continuous Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  check_repository:
    runs-on: ubuntu-latest
    steps:
    - name: Check repository
      run: |
        if [[ "${{ github.repository }}" != "OpenRHINO/code-chat-reviewer" ]]; then
          echo "The CD workflow runs only in the upstream OpenRHINO/code-chat-reviewer repository.\n"
          echo "If you need to run the CD workflow in a fork repo, you may customize this workflow."
          exit 0
        fi

  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'OpenRHINO/code-chat-reviewer'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: openrhino
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
          cd pr_review
          docker build -t openrhino/pr-review-gpt .
          docker push openrhino/pr-review-gpt
          cd ..

    - name: Set up Kubernetes environment
      uses: azure/k8s-set-context@v2
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Restart Deployment
      run: kubectl rollout restart deployment pr-review-gpt -n ${{ vars.NAMESPACE }}
